/**
 * Sat-line / desk satellite assembly recipe — phase spine 0..7.
 * Electrical pin locals come from sat-pins.ts (shared with mesh stubs).
 * Cage face anchors use life-size half-edge from RealPartSpec layout.
 */
import type { AssemblyRecipe } from "./assembly-recipe";
import { pinAnchorsForNode } from "./sat-pins";
import { deriveCageEdgeMm, LIFE_LAYOUT } from "./real-parts";

const CAGE_HALF = deriveCageEdgeMm() / 2;
const STAND_TOP_Y = LIFE_LAYOUT.standStemHeightMm + 5;

export const SAT_CLOCK_RECIPE: AssemblyRecipe = {
  templateId: "sat_clock",
  productLabel: "Desk satellite clock",
  parts: [
    {
      id: "stand",
      nodeId: "base",
      layer: "base",
      label: "Metal stand",
      colorKey: "steel",
      anchors: [{ name: "top", local: [0, STAND_TOP_Y, 0] }],
    },
    {
      id: "cage",
      nodeId: "frame",
      layer: "frame",
      label: "Brass wire cage",
      colorKey: "brass",
      anchors: [
        { name: "bottom", local: [0, -CAGE_HALF, 0] },
        { name: "mid-L", local: [-CAGE_HALF, 0, 0] },
        { name: "mid-R", local: [CAGE_HALF, 0, 0] },
        { name: "front", local: [0, 0, CAGE_HALF] },
        { name: "back", local: [0, 0, -CAGE_HALF] },
        { name: "top", local: [0, CAGE_HALF, 0] },
      ],
    },
    {
      id: "face-panel",
      nodeId: "face-panel",
      layer: "face",
      label: "Front face panel",
      colorKey: "panel",
    },
    {
      id: "rear-panel",
      nodeId: "rear-panel",
      layer: "power",
      label: "Rear service panel",
      colorKey: "panel",
    },
    {
      id: "battery",
      nodeId: "battery",
      layer: "power",
      label: "Li-ion cell",
      colorKey: "cell",
      anchors: pinAnchorsForNode("battery"),
    },
    {
      id: "straps",
      nodeId: "straps",
      layer: "power",
      label: "Battery straps",
      colorKey: "brass",
    },
    {
      id: "charger",
      nodeId: "charger",
      layer: "power",
      label: "TP4056 charger",
      colorKey: "pcb",
      anchors: pinAnchorsForNode("charger"),
    },
    {
      id: "brain",
      nodeId: "brain",
      layer: "brain",
      label: "ESP32-C3",
      colorKey: "pcb",
      anchors: pinAnchorsForNode("brain"),
    },
    {
      id: "face",
      nodeId: "face",
      layer: "face",
      label: "OLED display",
      colorKey: "oled",
      anchors: pinAnchorsForNode("face"),
    },
    {
      id: "sensor",
      nodeId: "sensor",
      layer: "sensor",
      label: "Sensor",
      colorKey: "sensor",
      anchors: pinAnchorsForNode("sensor"),
    },
    {
      id: "touch",
      nodeId: "touch",
      layer: "touch",
      label: "Touch switch",
      colorKey: "touch",
      anchors: pinAnchorsForNode("touch"),
    },
    {
      id: "solar-l",
      nodeId: "solar-l",
      layer: "wings",
      label: "Solar panel L",
      colorKey: "solar",
      anchors: pinAnchorsForNode("solar-l"),
    },
    {
      id: "solar-r",
      nodeId: "solar-r",
      layer: "wings",
      label: "Solar panel R",
      colorKey: "solar",
      anchors: pinAnchorsForNode("solar-r"),
    },
    {
      id: "spar-l",
      nodeId: "spar-l",
      layer: "wings",
      label: "Wing spar L",
      colorKey: "brass",
    },
    {
      id: "spar-r",
      nodeId: "spar-r",
      layer: "wings",
      label: "Wing spar R",
      colorKey: "brass",
    },
  ],
  joints: [
    {
      id: "j-stand-cage",
      parentPartId: "stand",
      childPartId: "cage",
      axis: [0, 1, 0],
      explodeDistance: 40,
    },
    {
      id: "j-cage-battery",
      parentPartId: "cage",
      childPartId: "battery",
      axis: [0, 0, -1],
      explodeDistance: 35,
    },
    {
      id: "j-battery-straps",
      parentPartId: "battery",
      childPartId: "straps",
      axis: [0, 1, 0],
      explodeDistance: 12,
    },
    {
      id: "j-cage-charger",
      parentPartId: "cage",
      childPartId: "charger",
      axis: [0, 0, -1],
      explodeDistance: 30,
    },
    {
      id: "j-cage-brain",
      parentPartId: "cage",
      childPartId: "brain",
      axis: [0, 0, 1],
      explodeDistance: 28,
    },
    {
      id: "j-cage-face",
      parentPartId: "cage",
      childPartId: "face",
      axis: [0, 0, 1],
      explodeDistance: 32,
    },
    {
      id: "j-cage-sensor",
      parentPartId: "cage",
      childPartId: "sensor",
      axis: [1, 0, 0.5],
      explodeDistance: 25,
    },
    {
      id: "j-cage-touch",
      parentPartId: "cage",
      childPartId: "touch",
      axis: [0, 1, 0],
      explodeDistance: 30,
    },
    {
      id: "j-cage-solar-l",
      parentPartId: "cage",
      childPartId: "solar-l",
      axis: [-1, 0.1, 0],
      explodeDistance: 45,
    },
    {
      id: "j-cage-solar-r",
      parentPartId: "cage",
      childPartId: "solar-r",
      axis: [1, 0.1, 0],
      explodeDistance: 45,
    },
    {
      id: "j-solar-spar-l",
      parentPartId: "solar-l",
      childPartId: "spar-l",
      axis: [-1, 0, 0],
      explodeDistance: 10,
    },
    {
      id: "j-solar-spar-r",
      parentPartId: "solar-r",
      childPartId: "spar-r",
      axis: [1, 0, 0],
      explodeDistance: 10,
    },
  ],
  phases: [
    {
      index: 0,
      id: "foundation",
      title: "Foundation",
      callout: "Place the slender metal stand — the product’s spine.",
      addsParts: ["stand"],
      addsJoints: [],
      addsNets: [],
      cameraHint: { position: [0.7, 0.6, 0.9], target: [0, 0.4, 0] },
    },
    {
      index: 1,
      id: "structure",
      title: "Structure",
      callout: "Seat the brass wire cube cage on the stand.",
      addsParts: ["cage", "face-panel", "rear-panel"],
      addsJoints: ["j-stand-cage"],
      addsNets: [],
      cameraHint: { position: [0.9, 1.0, 1.0], target: [0, 0.9, 0] },
    },
    {
      index: 2,
      id: "power",
      title: "Power bay",
      callout: "Battery in the cage with straps; TP4056 on the rear panel.",
      addsParts: ["battery", "straps", "charger"],
      addsJoints: ["j-cage-battery", "j-battery-straps", "j-cage-charger"],
      addsNets: ["bat", "gnd", "vbat", "power", "b+", "b-"],
      cameraHint: { position: [0.6, 1.1, -1.0], target: [0, 1.0, 0] },
    },
    {
      index: 3,
      id: "brain",
      title: "Brain",
      callout: "Mount the ESP32-C3 and feed it power from the charger.",
      addsParts: ["brain"],
      addsJoints: ["j-cage-brain"],
      addsNets: ["3v3", "vcc", "5v", "vin"],
      cameraHint: { position: [1.0, 1.0, 0.9], target: [0, 1.0, 0.1] },
    },
    {
      index: 4,
      id: "face",
      title: "Face",
      callout: "OLED on the front face — I2C to the brain.",
      addsParts: ["face"],
      addsJoints: ["j-cage-face"],
      addsNets: ["i2c", "sda", "scl", "oled"],
      cameraHint: { position: [0.3, 1.05, 1.3], target: [0, 1.05, 0.2] },
    },
    {
      index: 5,
      id: "sense",
      title: "Sense & touch",
      callout: "Sensor and touch pad complete the human interface.",
      addsParts: ["sensor", "touch"],
      addsJoints: ["j-cage-sensor", "j-cage-touch"],
      addsNets: ["touch", "ttp", "sht", "sensor", "gpio"],
      cameraHint: { position: [1.0, 1.3, 0.7], target: [0, 1.15, 0] },
    },
    {
      index: 6,
      id: "wings",
      title: "Wings",
      callout: "Solar panels on spars feed the charger.",
      addsParts: ["solar-l", "solar-r", "spar-l", "spar-r"],
      addsJoints: ["j-cage-solar-l", "j-cage-solar-r", "j-solar-spar-l", "j-solar-spar-r"],
      addsNets: ["solar", "pv"],
      cameraHint: { position: [1.2, 1.2, 0.6], target: [0, 1.05, 0] },
    },
    {
      index: 7,
      id: "complete",
      title: "Complete",
      callout: "Desk satellite assembled — orbit, peel phases, inspect nets.",
      addsParts: [],
      addsJoints: [],
      addsNets: [],
      cameraHint: { position: [0.95, 1.15, 1.05], target: [0, 0.95, 0] },
    },
  ],
  stepToPhase: {
    bamboo_base_drill: 0,
    wire_bend_frame: 1,
    cut_jumpers: 1,
    battery_id_poles: 2,
    usb_upload: 3,
    oled_desolder: 4,
    i2c_wiring: 4,
    touch_mount: 5,
    solar_panel_mount: 6,
    final_assembly: 7,
  },
};

export function getRecipeForTemplate(templateId: string): AssemblyRecipe | null {
  if (templateId === "sat_clock") return SAT_CLOCK_RECIPE;
  return null;
}
